name: Base 

on: [pull_request]

env:
    OP_RPC_URL: ${{secrets.OP_RPC_URL}}
    BASE_RPC_URL: ${{secrets.BASE_RPC_URL}}
    MOONBEAM_RPC_URL: ${{secrets.MOONBEAM_RPC_URL}}
    PRIMARY_FORK_ID: 1
    FOUNDRY_PROFILE: ci

jobs:
  live-system-integration-tests:
    name: Live System Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Give write permissions
        run: chmod -R +x proposals/mips/

      - name: Live System Integration Tests
        uses: nick-fields/retry@v3
        with:
           polling_interval_seconds: 30
           retry_wait_seconds: 60
           timeout_minutes: 50
           max_attempts: 3
           command: time forge test --match-contract LiveSystem -vvv --ffi

  fee-splitter-xwell-integration-tests:
    name: Fee Splitter/xWell Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Run Integration Tests
        uses: nick-fields/retry@v3
        with:
           polling_interval_seconds: 30
           retry_wait_seconds: 60
           timeout_minutes: 20
           max_attempts: 3
           # matches 2 contracts, they will run concurrently
           command: time forge test --match-contract 'xWellIntegrationTest|FeeSplitterIntegrationTest' --fork-url base -vvv --ffi

  erc4626-vault-integration-tests:
    name: ERC4626 Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Run Integration Test
        uses: nick-fields/retry@v3
        with:
           polling_interval_seconds: 30
           retry_wait_seconds: 60
           timeout_minutes: 20
           max_attempts: 3
           # since 'ERC4626' matches 4 contracts, they will run concurrently
           command: time forge test --match-contract ERC4626 --fork-url base -vvv --ffi

  cypher-integration-tests:
    name: Cypher Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Run Integration Test
        uses: nick-fields/retry@v3
        with:
           polling_interval_seconds: 30
           retry_wait_seconds: 60
           timeout_minutes: 20
           max_attempts: 3
           command: time forge test --match-contract CypherIntegrationTest --fork-url base -vvv 

