name: Optimism

on: [pull_request]

env:
  OP_RPC_URL: ${{secrets.OP_RPC_URL}}
  BASE_RPC_URL: ${{secrets.BASE_RPC_URL}}
  MOONBEAM_RPC_URL: ${{secrets.MOONBEAM_RPC_URL}}
  PRIMARY_FORK_ID: 2

jobs:
  live-system-integration-tests:
    name: Live System Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Give write permissions
        run: chmod -R +x proposals/mips/

      - name: Live System Integration Tests
        uses: nick-fields/retry@v3
        with:
           polling_interval_seconds: 30
           retry_wait_seconds: 60
           timeout_minutes: 20
           max_attempts: 3
           command: time forge test --match-contract LiveSystem -vvv --ffi

  xwell-integration-tests:
    name: xWell Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Run Integration Tests
        uses: nick-fields/retry@v3
        with:
           polling_interval_seconds: 30
           retry_wait_seconds: 60
           timeout_minutes: 20
           max_attempts: 3
           # matches 2 contracts, they will run concurrently
           command: time forge test --match-contract 'xWellIntegrationTest' --fork-url optimism -vvv --ffi

  chainlink-oev-wrapper:
    name: Chainlink OEV Wrapper Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Give write permissions
        run: chmod -R +x proposals/mips/

      - name: Run Integration Tests
        uses: nick-fields/retry@v3
        with:
           polling_interval_seconds: 30
           retry_wait_seconds: 60
           timeout_minutes: 20
           max_attempts: 3
           command: time forge test --mc "ChainlinkOEVWrapperIntegration" -vvv --ffi
