name: Unit Tests

on: [pull_request]

env:
  FOUNDRY_PROFILE: ci
 
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Environment
        uses: ./.github/actions

      - name: Run Unit Tests
        uses: nick-fields/retry@v3
        with:
           polling_interval_seconds: 30
           retry_wait_seconds: 60
           timeout_minutes: 20
           max_attempts: 3
           command: time forge test -vvv --match-contract UnitTest

      - name: Run MultiRewards Tests
        uses: nick-fields/retry@v3
        with:
           polling_interval_seconds: 30
           retry_wait_seconds: 60
           timeout_minutes: 20
           max_attempts: 3
           command: time forge test --match-path test/unit/MultiRewards.t.sol -vvv

